apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-processor
  namespace: trading-pipeline
  labels:
    app: spark-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-processor
  template:
    metadata:
      labels:
        app: spark-processor
    spec:
      containers:
      - name: spark-processor
        image: finnhub-spark-processor:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: CASSANDRA_HOST
          value: "cassandra"
        - name: SPARK_DRIVER_MEMORY
          value: "4g"
        - name: SPARK_EXECUTOR_MEMORY
          value: "8g"
        resources:
          requests:
            memory: "12Gi"
            cpu: "4"
          limits:
            memory: "16Gi"
            cpu: "8"
        volumeMounts:
        - name: checkpoint
          mountPath: /checkpoint
      volumes:
      - name: checkpoint
        persistentVolumeClaim:
          claimName: spark-checkpoint-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-checkpoint-pvc
  namespace: trading-pipeline
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi