apiVersion: 1

datasources:
  - name: Cassandra
    type: hadesarchitect-cassandra-datasource
    access: proxy
    url: cassandra:9042
    database: market_data
    basicAuth: false
    isDefault: true
    jsonData:
      keyspace: market_data
      consistency: ONE