global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'finnhub_producer'
    metrics_path: /metrics
    static_configs:
      - targets: ['finnhub-producer:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'kafka_jmx'
    static_configs:
      - targets: ['kafka:7071']   # jmx_prometheus_javaagent will listen here (see compose)
    metrics_path: /metrics

  - job_name: 'spark_jmx'
    static_configs:
      - targets: ['spark-processor:7072']

  - job_name: 'cassandra_exporter'
    static_configs:
      - targets: ['cassandra-exporter:8080']
