global:
  resolve_timeout: 5m

route:
  receiver: 'default'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'default'
    # add your integrations here. Example slack:
    # - slack_configs:
    #     - api_url: 'https://hooks.slack.com/services/XXXXX/XXXXX/XXXXX'
    #       channel: '#alerts'
    # For now default to just noop (can be expanded).
